import * as vscode from 'vscode';
import * as fs from 'fs';
import * as path from 'path';
import { spawn } from 'child_process';
import {
  PYGREENSENSE_CLI_COMMAND,
  PYGREENSENSE_CLI_MODULE,
} from './config';

export type RunResult = {
  code: number;
  stdout: string;
  stderr: string;
};

export async function runInVenv(
  pythonPath: string,
  args: string[],
  cwd: string,
  output: vscode.OutputChannel
): Promise<RunResult> {
  return new Promise((resolve, reject) => {
    output.appendLine(`$ ${pythonPath} ${args.join(' ')}`);
    const p = spawn(pythonPath, args, { cwd });

    let stdout = '';
    let stderr = '';

    p.stdout.on('data', (d) => {
      const s = String(d);
      stdout += s;
      output.appendLine(s);
    });

    p.stderr.on('data', (d) => {
      const s = String(d);
      stderr += s;
      output.appendLine(s);
    });

    p.on('error', reject);
    p.on('close', (code) => resolve({ code: code ?? -1, stdout, stderr }));
  });
}

type LaunchCommand = {
  command: string;
  args: string[];
};

function resolvePyGreenSenseLaunch(pythonPath: string): LaunchCommand {
  const scriptDir = path.dirname(pythonPath);
  const commandCandidates =
    process.platform === 'win32'
      ? [
          `${PYGREENSENSE_CLI_COMMAND}.exe`,
          `${PYGREENSENSE_CLI_COMMAND}.cmd`,
          `${PYGREENSENSE_CLI_COMMAND}-script.py`,
        ]
      : [PYGREENSENSE_CLI_COMMAND];

  // Prefer the console script generated by pip because the package
  // itself does not expose green_code_smell.__main__.
  for (const candidate of commandCandidates) {
    const candidatePath = path.join(scriptDir, candidate);
    if (!fs.existsSync(candidatePath)) {
      continue;
    }

    if (candidate.endsWith('.py')) {
      return { command: pythonPath, args: [candidatePath] };
    }

    return { command: candidatePath, args: [] };
  }

  return { command: pythonPath, args: ['-m', PYGREENSENSE_CLI_MODULE] };
}

/**
 * Runs PyGreenSense using its installed CLI entrypoint.
 */
export async function runPyGreenSense(
  pythonPath: string,
  workspaceRoot: string,
  targetFile: string,
  output: vscode.OutputChannel
): Promise<RunResult> {
  const launch = resolvePyGreenSenseLaunch(pythonPath);
  return runInVenv(launch.command, [...launch.args, targetFile], workspaceRoot, output);
}
